# Generated by Django 3.0.8 on 2020-08-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PL', 'planned'), ('IP', 'in processing'), ('RN', 'running'), ('FIN', 'finished')], max_length=20)),
                ('creation_date', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=20)),
            ],
        ),
    ]
